= Dataset Import Handler Example
:source-highlighter: highlightjs

== Important Links

* Created from template: https://github.com/VEuPathDB/example-dataset-import-handler
* Script Expectations: https://github.com/VEuPathDB/util-user-dataset-handler-server#script-expectations
* Config.yml Variables: https://veupathdb.github.io/util-user-dataset-handler-server

== Gene List Format
The gene list format has a single string on each line corresponding to a gene identifier. There should not be additional columns or spaces present on any line of the file.

== Usage

=== GeneList script

The script is implemented in Python ported from https://github.com/VEuPathDB/EuPathGalaxy. More details on the script's output expectations can be found https://github.com/VEuPathDB/EuPathGalaxy[here].

=== Jenkinsfile

The project Jenkinsfile tells the Jenkins build workflow how to build your
dataset handler.  Generally, you will only need to edit one line, which is the
build container name.

.Jenkinsfile
[source, groovy]
----
#!groovy

@Library('pipelib')
import org.veupathdb.lib.Builder

node('centos8') {
  sh "env"

  def builder = new Builder(this)

  builder.gitClone()
  builder.buildContainers([
    [ name: 'user-dataset-handler-gene-list' ] <1>
  ])
}
----
<1> This line configures the name of the image when it is built.  It should be
    similar to the example in name following the template
    `user-dataset-handler-{my-handler-name}`

=== Local Development
The easiest way to test locally is to run the import service end-to-end using https://github.com/VEuPathDB/service-user-dataset-import#running-locally[these instructions]. If this project is checked out in the same directory as the service, the service can be configured to use any locally staged changes when building the gene-list docker container.